sudo: required
services:
  - docker

before_install:
  - docker build -t michael4reynolds/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run michael4reynolds/react-test npm test -- --coverage

after_success:
  - docker build -t michael4reynolds/multi-client ./client
  - docker build -t michael4reynolds/multi-nginx ./nginx
  - docker build -t michael4reynolds/multi-server ./server
  - docker build -t michael4reynolds/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push michael4reynolds/multi-client
  - docker push michael4reynolds/multi-nginx
  - docker push michael4reynolds/multi-server
  - docker push michael4reynolds/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: complex-ebs
  env: complex-ebs-dev
  bucket_name: elasticbeanstalk-us-east-1-967042647185
  bucket_path: complex-ebs
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
